### ISSUE TITLE
Codec name and other properties supplied from outside foundation

### ISSUE THREAD

**Issue by bangnoise** [GregBakker/adobe-cc-codec-foundation#2]
We should have CMake variables for codec name and other properties which can be used as defines at compile time for compilation of foundation source files as well as the macOS resource build stage for the AE SDK. Ideally these could be supplied by the user of foundation outside of foundation from eg a template CMakeLists.txt for the parent project.

**Comment by GregBakker** [comment]
- [x] Add CMake variables
- [ ] Update documentation.

**Comment by GregBakker** [comment]
Now present in main branch, will be in foundation release 0.1.0
